# Generated by Django 3.1.1 on 2020-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200912_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(upload_to='quizzes/thumbnails'),
        ),
    ]
